# Enable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable detailed logging
CONFIG_ZMK_USB_LOGGING=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_EC11_LOG_LEVEL_DBG=y
CONFIG_SENSOR_LOG_LEVEL_DBG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y

# Enable sensor debugging
CONFIG_SENSOR=y
CONFIG_SENSOR_LOG_LEVEL_DBG=y

# Enable GPIO debugging
CONFIG_GPIO_LOG_LEVEL_DBG=y